### ISSUE TITLE
Use via volume

### ISSUE THREAD

**Issue by gmuellerinform** [fivexl/lprobe#7]
Hi! Great tool. I use it via volume mounts, so there is no need to build new images for existing tools. Maybe you can add it to the docs:

```
services:
  gitea:
    image: gitea/gitea:1.19.2
    volumes:
      - ./Lprobe:/Lprobe
    ...
    healthcheck:
      test: /Lprobe ...
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 3s
```
